enable-magisk-update = true

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
arch = "arm64-v8a"
version = "19.05.36"
build-mode = "both"
included-patches = "'Visual preferences icons'"
excluded-patches = "'Custom branding icon for YouTube' 'Custom branding name for YouTube' 'Hook download actions'"

[Music]
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
arch = "arm64-v8a"
build-mode = "both"
excluded-patches = "'Custom branding icon for YouTube Music' 'Custom branding name for YouTube Music'"

[Reddit]
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit/"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
arch = "arm64-v8a"

[Twitch]
apkmirror-dlurl = "https://apkmirror.com/apk/twitch-interactive-inc/twitch/"
arch = "arm64-v8a"

[Twitter]
apkmirror-dlurl = "https://apkmirror.com/apk/twitter-inc/twitter/"

[Strava]
apkmirror-dlurl = "https://www.apkmirror.com/apk/strava-inc/strava-running-and-cycling-gps/"
build-mode = "both"
